name: kotlin_lint

on:
  push:
    branches-ignore:
      - "*"
  pull_request:
    paths:
      - "**/*.kt"
      - ".github/workflows/kotlin_lint.yml"

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2

      - name: "ktlint"
        uses: "vroy/gha-kotlin-linter@v1"