name: "🧪 Run Tests"

on: [push, pull_request]

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx6g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

jobs:
  build-and-test:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 19

      - name: Set up Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build --full-stacktrace

      - name: Run Tests
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}  # Use the secret stored in GitHub
        uses: gradle/gradle-build-action@v3
        with:
          arguments: test --info --full-stacktrace

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 'test-reports'
          path: '**/build/reports/tests/**'
